[2024-07-09T17:39:44.253+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T17:39:42.965482+00:00 [queued]>
[2024-07-09T17:39:44.259+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T17:39:42.965482+00:00 [queued]>
[2024-07-09T17:39:44.260+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T17:39:44.273+0000] {taskinstance.py:2217} INFO - Executing <Task(PapermillOperator): workspace> on 2024-07-09 17:39:42.965482+00:00
[2024-07-09T17:39:44.280+0000] {standard_task_runner.py:60} INFO - Started process 3778 to run task
[2024-07-09T17:39:44.283+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pesquisa_industrial_anual_empresas', 'workspace', 'manual__2024-07-09T17:39:42.965482+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/pesquisa_industrial_anual_empresas/dags.py', '--cfg-path', '/tmp/tmptuv4n6_f']
[2024-07-09T17:39:44.290+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask workspace
[2024-07-09T17:39:44.344+0000] {task_command.py:423} INFO - Running <TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T17:39:42.965482+00:00 [running]> on host 049690d4da25
[2024-07-09T17:39:44.443+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='observatorio@sistemafiea.com.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pesquisa_industrial_anual_empresas' AIRFLOW_CTX_TASK_ID='workspace' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T17:39:42.965482+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T17:39:42.965482+00:00'
[2024-07-09T17:39:44.444+0000] {execute.py:83} INFO - Input Notebook:  /opt/***/dags/pesquisa_industrial_anual_empresas/notebooks/workspace.ipynb
[2024-07-09T17:39:44.445+0000] {execute.py:84} INFO - Output Notebook: /opt/***/dags/resultado/pesquisa_industrial_anual_empresas_workspace_2024-07-09.ipynb
[2024-07-09T17:39:45.872+0000] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-07-09T17:39:52.414+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[4], line 4
      1 # url para o cojunto de dados 
      2 url = "https://servicodados.ibge.gov.br/api/v3/agregados/1839/periodos/2022/variaveis/630?localidades=N1[all]"
----> 4 response = requests.get(url)
      5 data = response.json()
      7 rdd = spark.sparkContext.parallelize(data)

NameError: name 'requests' is not defined

[2024-07-09T17:39:52.427+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pesquisa_industrial_anual_empresas, task_id=workspace, execution_date=20240709T173942, start_date=20240709T173944, end_date=20240709T173952
[2024-07-09T17:39:52.458+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task workspace (
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[4], line 4
      1 # url para o cojunto de dados 
      2 url = "https://servicodados.ibge.gov.br/api/v3/agregados/1839/periodos/2022/variaveis/630?localidades=N1[all]"
----> 4 response = requests.get(url)
      5 data = response.json()
      7 rdd = spark.sparkContext.parallelize(data)

NameError: name 'requests' is not defined
; 3778)
[2024-07-09T17:39:52.507+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T17:39:52.528+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
